module liphte.html.abstract {
    export abstract class Markup {

        protected tags: string[] = Object.getOwnPropertyNames(Markup.prototype);

        a(...attributesAndContent){}
        abbr(...attributesAndContent){}
        address(...attributesAndContent){}
        area(...attributesAndContent){}
        article(...attributesAndContent){}
        aside(...attributesAndContent){}
        audio(...attributesAndContent){}
        b(...attributesAndContent){}
        base(...attributesAndContent){}
        bdi(...attributesAndContent){}
        bdo(...attributesAndContent){}
        blockquote(...attributesAndContent){}
        body(...attributesAndContent){}
        br(...attributesAndContent){}
        button(...attributesAndContent){}
        canvas(...attributesAndContent){}
        caption(...attributesAndContent){}
        cite(...attributesAndContent){}
        code(...attributesAndContent){}
        col(...attributesAndContent){}
        colgroup(...attributesAndContent){}
        command(...attributesAndContent){}
        datalist(...attributesAndContent){}
        dd(...attributesAndContent){}
        del(...attributesAndContent){}
        details(...attributesAndContent){}
        dfn(...attributesAndContent){}
        div(...attributesAndContent){}
        dl(...attributesAndContent){}
        dt(...attributesAndContent){}
        em(...attributesAndContent){}
        embed(...attributesAndContent){}
        fieldset(...attributesAndContent){}
        figcaption(...attributesAndContent){}
        figure(...attributesAndContent){}
        footer(...attributesAndContent){}
        form(...attributesAndContent){}
        h1(...attributesAndContent){}
        h2(...attributesAndContent){}
        h3(...attributesAndContent){}
        h4(...attributesAndContent){}
        h5(...attributesAndContent){}
        h6(...attributesAndContent){}
        head(...attributesAndContent){}
        header(...attributesAndContent){}
        hgroup(...attributesAndContent){}
        hr(...attributesAndContent){}
        html(...attributesAndContent){}
        i(...attributesAndContent){}
        iframe(...attributesAndContent){}
        img(...attributesAndContent){}
        input(...attributesAndContent){}
        ins(...attributesAndContent){}
        kbd(...attributesAndContent){}
        keygen(...attributesAndContent){}
        label(...attributesAndContent){}
        legend(...attributesAndContent){}
        li(...attributesAndContent){}
        link(...attributesAndContent){}
        map(...attributesAndContent){}
        mark(...attributesAndContent){}
        menu(...attributesAndContent){}
        meta(...attributesAndContent){}
        meter(...attributesAndContent){}
        nav(...attributesAndContent){}
        noscript(...attributesAndContent){}
        object(...attributesAndContent){}
        ol(...attributesAndContent){}
        optgroup(...attributesAndContent){}
        option(...attributesAndContent){}
        output(...attributesAndContent){}
        p(...attributesAndContent){}
        param(...attributesAndContent){}
        pre(...attributesAndContent){}
        progress(...attributesAndContent){}
        q(...attributesAndContent){}
        rp(...attributesAndContent){}
        rt(...attributesAndContent){}
        ruby(...attributesAndContent){}
        s(...attributesAndContent){}
        samp(...attributesAndContent){}
        script(...attributesAndContent){}
        section(...attributesAndContent){}
        select(...attributesAndContent){}
        small(...attributesAndContent){}
        source(...attributesAndContent){}
        span(...attributesAndContent){}
        strong(...attributesAndContent){}
        style(...attributesAndContent){}
        sub(...attributesAndContent){}
        summary(...attributesAndContent){}
        sup(...attributesAndContent){}
        table(...attributesAndContent){}
        tbody(...attributesAndContent){}
        td(...attributesAndContent){}
        textarea(...attributesAndContent){}
        tfoot(...attributesAndContent){}
        th(...attributesAndContent){}
        thead(...attributesAndContent){}
        time(...attributesAndContent){}
        title(...attributesAndContent){}
        tr(...attributesAndContent){}
        track(...attributesAndContent){}
        u(...attributesAndContent){}
        ul(...attributesAndContent){}
        var(...attributesAndContent){}
        video(...attributesAndContent){}
        wbr(...attributesAndContent){}
    }
}
